In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
tokenizer = Tokenizer()


In [3]:
with open("data.txt", "r", encoding="utf-8") as file:
    text = file.read()

print(text[:200])  # first 200 characters


Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle.

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, g


In [4]:
tokenizer.fit_on_texts([text])

In [5]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'a': 5,
 'i': 6,
 '”': 7,
 'in': 8,
 'that': 9,
 'it': 10,
 'he': 11,
 'was': 12,
 'you': 13,
 'his': 14,
 'is': 15,
 'my': 16,
 'have': 17,
 'with': 18,
 'as': 19,
 'had': 20,
 'at': 21,
 'which': 22,
 'for': 23,
 'be': 24,
 'not': 25,
 'me': 26,
 'but': 27,
 'from': 28,
 'we': 29,
 'this': 30,
 'said': 31,
 'upon': 32,
 'there': 33,
 'holmes': 34,
 'him': 35,
 'so': 36,
 'her': 37,
 'she': 38,
 'all': 39,
 '’': 40,
 'been': 41,
 'your': 42,
 'on': 43,
 'very': 44,
 'by': 45,
 'one': 46,
 'are': 47,
 '“i': 48,
 'were': 49,
 'an': 50,
 'no': 51,
 'would': 52,
 'out': 53,
 'what': 54,
 'then': 55,
 'up': 56,
 'when': 57,
 'man': 58,
 'could': 59,
 'has': 60,
 'do': 61,
 'into': 62,
 'or': 63,
 'little': 64,
 'will': 65,
 'who': 66,
 'mr': 67,
 'if': 68,
 'some': 69,
 'down': 70,
 'see': 71,
 'now': 72,
 'our': 73,
 'should': 74,
 'may': 75,
 'am': 76,
 'us': 77,
 'over': 78,
 'they': 79,
 'can': 80,
 'more': 81,
 'think': 82,
 'about': 83,
 'mu

In [6]:
len(tokenizer.word_index)

8931

In [7]:
for sentence in text.split('.'):
    print(sentence.strip())


Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle
This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever
You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online
Title: The Adventures of Sherlock Holmes
Author: Arthur Conan Doyle
Release Date: November 29, 2002 [EBook #1661]
Last Updated: May 20, 2019
Language: English
Character set encoding: UTF-8
*** START OF THIS PROJECT GUTENBERG EBOOK THE ADVENTURES OF SHERLOCK HOLMES ***



Produced by an anonymous Project Gutenberg volunteer and Jose Menendez
cover



The Adventures of Sherlock Holmes



by Arthur Conan Doyle
I
A SCANDAL IN BOHEMIA


I
To Sherlock Holmes she is always _the_ woman
I have seldom heard him
mention her under any other name
In his eyes she eclipses and
predominates the whole of her sex
It was not that he felt any emotion
akin to love for Irene Adler
All emotions, and that one p

In [8]:
input_sequence=[]
for sentence in text.split('.'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence.strip()])[0]
    print(tokenized_sentence)

    for i in range(1, len(tokenized_sentence)):
        input_sequence.append(tokenized_sentence[:i+1])

[4778, 145, 4779, 1, 1016, 4, 128, 34, 45, 611, 2233, 2234]
[30, 1017, 15, 23, 1, 275, 4, 394, 2235, 21, 51, 1674, 2, 18, 572, 51, 3396, 3397]
[13, 75, 815, 10, 213, 10, 124, 63, 2236, 275, 10, 262, 1, 480, 4, 1, 145, 131, 654, 2237, 18, 30, 1017, 63, 2238]
[2664, 1, 1016, 4, 128, 34]
[4780, 611, 2233, 2234]
[4781, 1018, 4782, 4783, 4784, 1017, 2239, 139, 3398, 75, 3399, 4785]
[3400, 1092]
[573, 243, 4786, 4787, 1468]
[719, 4, 30, 145, 131, 1017, 1, 1016, 4, 128, 34, 1928, 45, 50, 3401, 145, 131, 2665, 2, 3402, 3403]
[1675, 1, 1016, 4, 128, 34, 45, 611, 2233, 2234]
[6]
[5, 937, 8, 1019, 6]
[3, 128, 34, 38, 15, 229, 1, 221]
[6, 17, 1676, 116, 35, 3404, 37, 262, 89, 90, 214]
[8, 14, 151, 38, 4788, 2, 4789, 1, 283, 4, 37, 4790]
[10, 12, 25, 9, 11, 356, 89, 1929, 2666, 3, 655, 23, 816, 720]
[39, 4791, 2, 9, 46, 1469, 49, 4792, 3, 14, 522, 2667, 27, 2240, 4793, 227]
[11, 12, 6, 170, 10, 1, 142, 1470, 1020, 2, 2241, 690, 9, 1, 721, 60, 189, 27, 19, 5, 1471, 11, 52, 17, 612, 184, 8, 5, 2242, 

In [9]:
input_sequence

[[4778, 145],
 [4778, 145, 4779],
 [4778, 145, 4779, 1],
 [4778, 145, 4779, 1, 1016],
 [4778, 145, 4779, 1, 1016, 4],
 [4778, 145, 4779, 1, 1016, 4, 128],
 [4778, 145, 4779, 1, 1016, 4, 128, 34],
 [4778, 145, 4779, 1, 1016, 4, 128, 34, 45],
 [4778, 145, 4779, 1, 1016, 4, 128, 34, 45, 611],
 [4778, 145, 4779, 1, 1016, 4, 128, 34, 45, 611, 2233],
 [4778, 145, 4779, 1, 1016, 4, 128, 34, 45, 611, 2233, 2234],
 [30, 1017],
 [30, 1017, 15],
 [30, 1017, 15, 23],
 [30, 1017, 15, 23, 1],
 [30, 1017, 15, 23, 1, 275],
 [30, 1017, 15, 23, 1, 275, 4],
 [30, 1017, 15, 23, 1, 275, 4, 394],
 [30, 1017, 15, 23, 1, 275, 4, 394, 2235],
 [30, 1017, 15, 23, 1, 275, 4, 394, 2235, 21],
 [30, 1017, 15, 23, 1, 275, 4, 394, 2235, 21, 51],
 [30, 1017, 15, 23, 1, 275, 4, 394, 2235, 21, 51, 1674],
 [30, 1017, 15, 23, 1, 275, 4, 394, 2235, 21, 51, 1674, 2],
 [30, 1017, 15, 23, 1, 275, 4, 394, 2235, 21, 51, 1674, 2, 18],
 [30, 1017, 15, 23, 1, 275, 4, 394, 2235, 21, 51, 1674, 2, 18, 572],
 [30, 1017, 15, 23, 1, 275,

In [10]:
#need to apply padding to the input sequences so that they are all of the same length. This is important for training the LSTM model, as it requires inputs of uniform size.
maxLen=max([len(x) for x in input_sequence])


In [19]:
maxLen

105

In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequence, maxlen=maxLen, padding='pre')

In [12]:
padded_input_sequences

array([[   0,    0,    0, ...,    0, 4778,  145],
       [   0,    0,    0, ..., 4778,  145, 4779],
       [   0,    0,    0, ...,  145, 4779,    1],
       ...,
       [   0,    0,    0, ...,    3,  360,   83],
       [   0,    0,    0, ...,  360,   83,  358],
       [   0,    0,    0, ...,   83,  358, 1671]],
      shape=(104746, 105), dtype=int32)

In [13]:
# now our dataset is ready for training. The next steps would typically involve splitting the data into features and labels, defining the LSTM model architecture.
# the last number in each padded_input_sequences is the label (the next word to predict), and the rest are the features (the previous words). So we can split the data accordingly.
X=padded_input_sequences[:,:-1]
y=padded_input_sequences[:,-1]

In [14]:
X

array([[   0,    0,    0, ...,    0,    0, 4778],
       [   0,    0,    0, ...,    0, 4778,  145],
       [   0,    0,    0, ..., 4778,  145, 4779],
       ...,
       [   0,    0,    0, ..., 8931,    3,  360],
       [   0,    0,    0, ...,    3,  360,   83],
       [   0,    0,    0, ...,  360,   83,  358]],
      shape=(104746, 104), dtype=int32)

In [15]:
y

array([ 145, 4779,    1, ...,   83,  358, 1671],
      shape=(104746,), dtype=int32)

In [16]:
#take this as a classification problem, we need to one-hot encode the labels. The number of classes will be equal to the size of the vocabulary (i.e., the number of unique words in the text).
#the output of the one-hot encoding will be a binary matrix representation of the labels, where each row corresponds to a label and each column corresponds to a class (word in the vocabulary). The value at a given row and column will be 1 if the label corresponds to that class, and 0 otherwise.
from tensorflow.keras.utils import to_categorical
y=to_categorical(y, num_classes=len(tokenizer.word_index)+1)
#we add 1 to the number of classes because the tokenizer's word index starts from 1, and we need to account for the 0 index as well during onehot encoding.

In [17]:
y.shape

(104746, 8932)

In [18]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(104746, 8932))

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(8932,100,input_length =105, input_shape=(105,)))
model.add(LSTM(150))
model.add(Dense(8932,activation='softmax'))

e:\DEEP LEARNING\RNN\rnn.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
e:\DEEP LEARNING\RNN\rnn.venv\Lib\site-packages\keras\src\layers\core\embedding.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [25]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
X.shape

(104746, 104)

In [ ]:
model.summary()
#input dimension=100
# in embedding layer- for every word in a sentence, we will have a 100-dimensional vector representation. The input_length=105 means that each input sequence will be of length 105 (the maximum length of the sequences after padding).
#hence param for embedding layer= 8932*100=893300 since there are 8932 unique words in the vocabulary and each word is represented by a 100-dimensional vector.

#in lstm layer, the timesteps will be 105 (the length of the input sequences), and the number of features will be 100 (the dimensionality of the word embeddings).
#the output will be of (1,150) since we have 150 units in the LSTM layer. we know diemensionality of H(t) is equal to number of nodes in LSTM layer.

#in the dense layer, the input is the 150-dimensional output from the LSTM layer, and the output is a 8932-dimensional vector (the size of the vocabulary). The softmax activation function is used to convert the output into a probability distribution over the vocabulary.

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 105, 100)       │       893,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8932)           │     1,348,732 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,392,532 (9.13 MB)

 Trainable params: 2,392,532 (9.13 MB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.fit(X, y, epochs=60, verbose=1)

Epoch 1/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 269s 82ms/step - accuracy: 0.0856 - loss: 6.3042
Epoch 2/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 261s 80ms/step - accuracy: 0.1361 - loss: 5.4723
Epoch 3/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 254s 78ms/step - accuracy: 0.1591 - loss: 5.0508
Epoch 4/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 251s 77ms/step - accuracy: 0.1779 - loss: 4.6815
Epoch 5/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 264s 81ms/step - accuracy: 0.1973 - loss: 4.3494
Epoch 6/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 272s 83ms/step - accuracy: 0.2215 - loss: 4.0447
Epoch 7/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 267s 81ms/step - accuracy: 0.2500 - loss: 3.7594
Epoch 8/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 278s 85ms/step - accuracy: 0.2851 - loss: 3.4940
Epoch 9/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 274s 84ms/step - accuracy: 0.3214 - loss: 3.2489
Epoch 10/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 275s 84ms/step - accuracy: 0.3564 - loss: 3.0264
Epoch 11/60
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 276s 84ms/step - accuracy: 0.3927 - loss: 2.82

In [30]:
word="He"

#tokenize
token_text=tokenizer.texts_to_sequences([word])[0]
#padding
pad_text=pad_sequences([token_text], maxlen=105, padding='pre')
print(pad_text)



[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0 11]]


In [31]:
#predict the next word
model.predict(pad_text).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


(1, 8932)

In [32]:
import numpy as np

In [33]:
np.argmax(model.predict(pad_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


np.int64(12)

In [34]:
tokenizer.index_word[np.argmax(model.predict(pad_text))]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


'was'

In [37]:
word2="enough"
for i in range(5):
    
    token_text=tokenizer.texts_to_sequences([word2])[0]
    pad_text=pad_sequences([token_text], maxlen=105, padding='pre')
    predicted_word_index=np.argmax(model.predict(pad_text))
    predicted_word=tokenizer.index_word[predicted_word_index]
    print(predicted_word)
    word2+= " " + predicted_word

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
note
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
’
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
“‘is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
to


In [38]:
word3="I carefully examined"
for i in range(3):
    token_text=tokenizer.texts_to_sequences([word3])[0]
    pad_text=pad_sequences([token_text], maxlen=105, padding='pre')
    predicted_word_index=np.argmax(model.predict(pad_text))
    predicted_word=tokenizer.index_word[predicted_word_index]   
    print(predicted_word)
    print(word3 + " " + predicted_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
as
I carefully examined as
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
as
I carefully examined as
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
as
I carefully examined as
